marc2332/freya

- freya/src/lib.rs
Adds some docs about the three different methods to launch windows:
- `launch()`
- `launch_with_title()`
- `launch_cfg()`
> feat: Document launch methods

- components/src/slider.rs
- examples/text.rs
Useful for syncing state between restarts, like [here](https://github.com/trickypr/carpet/blob/0e7868d8fc7c8b9313a460c91ce53eff178bf87c/src/frontend/sound.rs#L34).
> refactor: `Slider` now manages its value via state

- Cargo.lock
- components/src/input.rs
- components/src/lib.rs
- elements/Cargo.toml
- elements/src/events.rs
- elements/src/lib.rs
- examples/input.rs
- renderer/Cargo.toml
- renderer/src/lib.rs
- renderer/src/work_loop.rs
- Adds support for `keydown` and `keyup` events.
- Add a new `Input` component
- Add a new example showcasing the Input component:
> feat: keydown & keyup events support

- elements/src/lib.rs
- examples/center.rs
- layout/src/lib.rs
- state/src/node.rs
This adds a new `display` attribute, with two modes `normal` and `center`.
The center mode will first calculate it's inner children layout as usually, then with this information, it will calculate the according centered position and size, and finally recalculate it's inner children layout with the new position and size.
I added an example `center.rs` to showcase this:
> feat: Center display mode

- Cargo.lock
- hooks/Cargo.toml
- hooks/src/use_animation.rs
[Tween](https://crates.io/crates/tween/versions) v1.0.0 has been magically removed from crates.io, this PR updates Tween to v2
> fix: Update tween

- Cargo.lock
- elements/src/lib.rs
- examples/camera.rs
- hooks/Cargo.toml
- hooks/src/lib.rs
- hooks/src/use_camera.rs
- renderer/src/renderer.rs
- state/Cargo.toml
- state/src/custom_attributes.rs
- state/src/references.rs
closes https://github.com/marc2332/freya/issues/68
- Adds a new `use_camera` hook
- Adds a new `image_reference` to the `image` element which allows to update an image without having to re-render the component
Example: 
```rust
fn app(cx: Scope) -> Element {
let (image_reference, camera_error) = use_camera(cx, CameraSettings::default());
render!(
rect {
width: "100%",
height: "100%",
padding: "100",
shadow: "0 10 150 40 black",
if let Some(err) = camera_error.get() {
rsx!(
label {
color: "black",
"{err}"
}
)
} else {
rsx!(
image {
width: "100%",
height: "100%",
image_reference: image_reference
}
)
}
}
)
```
> feat: use_camera

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- examples.sh
- freya/Cargo.toml
- layout/Cargo.toml
- processor/Cargo.toml
- readme.md
- renderer/Cargo.toml
- state/Cargo.toml
- testing/Cargo.toml
Closes https://github.com/marc2332/freya/issues/65
- Remove the `x11` feature
- Enable x11 support in `skia-safe` by default
> feat: Update Skia to 0.58.0 and remove "x11" feature

- examples/canvas.rs
- examples/editor.rs
- examples/virtual_scroll_view.rs
- hooks/src/lib.rs
- hooks/src/text_editor.rs
- hooks/src/use_editable.rs
- hooks/tests/use_editable.rs
- new `TextEditor` trait meant to hold a `Rope` and a `TextCursor`.
-  `use_editable` uses the new `UseEditableText` struct which implements `TextEditor`
> feat: Move text editing into a separate trait

- Cargo.lock
- layout/src/lib.rs
- renderer/src/elements/label.rs
- renderer/src/elements/paragraph.rs
- state/Cargo.toml
- state/src/font_style.rs
- state/src/lib.rs
`font_family` attribute now supports multiple fonts as fallback.
```rust
fn app(cx: Scope) -> Element {
render!(
label {
font_family: "Font A, Font B if A doesn't exist",
"Hello World!"
}
)
}
```
> feat: Multiple font families support

- Cargo.lock
- components/src/gesture_area.rs
- freya/src/lib.rs
- hooks/src/use_animation.rs
- hooks/src/use_focus.rs
- hooks/src/use_node.rs
- hooks/tests/use_editable.rs
- testing/Cargo.toml
- testing/src/config.rs
- testing/src/lib.rs
- testing/tests/test.rs
- new `TestingConfig` to simplify the configuration of the `TestingHandler`
- timeout the vdom polling, 16ms by default
> feat: Improvements in `freya-testing`

- elements/src/events/keyboard.rs
Closes https://github.com/marc2332/freya/issues/181
> fix: Space is inserted twice when using the shift modifier

- book/src/guides/style.md
- state/src/values/color.rs
- state/tests/parse_color.rs
Adds support for `hsl` colors in addition to the current `rgb` colors. These offer a more human-readable way to interpret sRGB colors, and offers a nice opportunity for making color systems based on hue. Two versions of the syntax are supported (same as CSS):
- Unitless (S/L/A components are 0.0-1.0): `hsl(28, 0.8, 0.5, 0.25)`
- Units (S/L/A components are 0% - 100%): `hsl(28deg, 80%, 50%, 25%)`
In the future, i'd like to also explore raw hex values (e.g. `#fff`) and wider color spaces than just SRGB (far future).
> feat: HSL color support

- book/src/guides/effects.md
- book/src/guides/style.md
- components/src/loader.rs
- examples/i18n.rs
- examples/rotate.rs
- state/src/transform.rs
- state/src/values/color.rs
- state/tests/parse_color.rs
This is an initial fix-up of some inconsistencies in freya's styling values.
- Removes the "unitless" form of `hsl` colors (`hsl(45, 0.5, 0.1, 0.2, 0.3)`), instead preferring the more explicit `hsl(45deg, 50%, 10%, 20%, 30%)` syntax.
- Makes `rotate` attribute use `deg` units.
This makes it consistent with the required units in `linear-gradient`. Let me know if any of this needs further discussion or whatnot.
> refactor(breaking): Consistency for rotation units

- torin/src/torin.rs
> fix: Avoid endless dirty-check nodes on torin

- Cargo.toml
- README.md
- book/src/guides/getting_started.md
- components/src/drag_drop.rs
- components/src/dropdown.rs
- devtools/src/hooks/mod.rs
- devtools/src/hooks/use_selected_node.rs
- devtools/src/lib.rs
- devtools/src/node.rs
- devtools/src/property.rs
- devtools/src/tab.rs
- devtools/src/tabs/layout.rs
- devtools/src/tabs/style.rs
- devtools/src/tabs/tree.rs
- elements/src/elements.rs
- examples/drag_drop.rs
- examples/ui.rs
Adapt freya to Dioxus v0.4 changes
> feat: Dioxus v0.4 support

- crates/renderer/src/window.rs
When resizing really slowly it sometimes stops responding to user input.
The `resize` function on `App` clears the layout.
Normally the OS would automatically schedule a redraw, but at least on Mac OS this doesn't always happen.
Without calling another redraw the layout remains empty, making it impossible to process input events. 
Manually requesting a redraw from the `WindowEnv` `resize` function fixes the problem.
> fix: Manually request redraw after resize on macOS

- book/src/differences_with_dioxus.md
The torin link was outdated. This updates it and also adds a permalink which will never "expire", unless the repository is deleted, or @marc2332 changes his name.
> fix(docs): Update Torin's link in differences with Dioxus

- .github/workflows/rust.yml
- crates/dom/Cargo.toml
- crates/dom/src/dom_adapter.rs
- crates/torin/Cargo.toml
- crates/torin/benches/bench.rs
- crates/torin/src/dom_adapter.rs
- crates/torin/src/torin.rs
- crates/torin/tests/test.rs
Depends on https://github.com/marc2332/freya/pull/314
> feat: Skip measuring of cached siblings in layout

- .github/workflows/rust.yml
- crates/dom/src/dom_adapter.rs
- crates/torin/Cargo.toml
- crates/torin/benches/bench.rs
- crates/torin/src/dom_adapter.rs
- crates/torin/src/torin.rs
- crates/torin/tests/test.rs
> Revert "feat: Skip measuring of cached siblings in layout"

- crates/components/src/input.rs
- examples/password.rs
- InputIsHidden enum where state Hidden contains a char that is used to hide chars of the input
- If input is hidden we use rust repeat method on the obfuscation char
- Example using hidden input for password input(also includes ability to show and hide the password)
- Change the enum to string*
- Wrong behavior with special chars like `\n` or `\t`**
-----------------------------------------------------------------------------------------------------
*This would make it not typesafe and introduce addtional checks to prevent bugs
**Should we block input of special chars or exclude some of the charecters from hiding
> feat: Password mode for `Input` component

- crates/components/src/input.rs
- crates/hooks/src/rope_editor.rs
Current cursor position never should not be after actual text string length so we need anyway fix it while updating text.
Quick fix for #348.
> fix: Update cursor position after updating text

- crates/components/src/cursor_area.rs
- crates/hooks/src/use_platform.rs
Depends on https://github.com/marc2332/freya/pull/330
> feat: `set_cursor` shortcut

- crates/components/src/cursor_area.rs
- crates/hooks/src/use_platform.rs
> Revert "feat: `set_cursor` shortcut"

- crates/core/src/events_processor.rs
> Revert "fix: `mouseenter` wasn't being emitted when `mouseover` was emitted at the same time"

- crates/components/src/button.rs
- crates/components/src/slider.rs
- crates/components/src/switch.rs
Closes https://github.com/marc2332/freya/issues/198
Show the Hand cursor when hovering the Button, Slider and Switch components
> feat: Show the Hand cursor when hovering the `Button`, `Slider` and `Switch` components

- crates/core/src/events/dom_events.rs
- crates/core/src/events/elements_state.rs
- crates/core/src/events/events_measurer.rs
- crates/elements/src/events/keyboard.rs
- crates/elements/src/events/mouse.rs
- crates/elements/src/events/pointer.rs
- crates/elements/src/events/touch.rs
- crates/elements/src/events/wheel.rs
Send `mouseleave` before `mouseover` for example
> feat: Reorder events based on their priority

- crates/core/src/layout/layers.rs
Closes https://github.com/marc2332/freya/issues/402
> feat: Skip text spans when traversing the DOM

- book/src/guides/layout.md
> so in this case, the `rect` width will be defined bu the width of `label`:
into:
> so in this case, the `rect` width will be equivalent to the width of `label`:
> Fix wording in book

- .gitignore
- crates/renderer/src/config.rs
Trying to load icons for images that have a smaller or larger bit depth than 32 fails. This fixes that by converting the `DynamicImage` to a standard format, so the bytes are formatted correctly.
> Fix window icons which don't have a 32 bit depth

- book/src/guides/components.md
Previously, the components were listed out manually. However, that means that the list will not be up-to-date, because new components are being added, or perhaps removed/renamed. This PR removes the list of components and instead links to the `components` module API docs, section "Functions". The old list linked there anyway, and it was indeed missing certain components.
> book: Add always up-to-date component reference

- book/src/index.md
I was going through the book and noticed that some APIs in it (e.g., `position`) are not in the crates.io version (currently `0.1.8`). This PR just adds a warning at the beginning of the book. I know there's a note saying that the book is not always accurate, but it's not very helpful and explicit in this particular case.
> Mention the fact that the book uses some APIs from the git version

- book/src/guides/theming.md
The book says that the default theme is `DARK_THEME`, but it's actually `LIGHT_THEME`.
> book: Fix mistake in theming chapter

- examples/password.rs
This forwards changes from https://github.com/marc2332/freya/commit/e37f66390671552235ab216eefeb62040cc846af to the password example.
> Fix error in password example

- crates/elements/src/definitions.rs
Defined property `decoraton_color` -> `decoration_color`. This was causing an error in one of the examples. Note that this is technically a breaking change.
> Fix typo in `rect` prop

- crates/freya/src/_docs/animating.rs
- crates/freya/src/_docs/theming.rs
Instead of using `> Message`, we should use `<div class="warning">Message</div>`. Comparison:
> Versioned docs: better warnings + fix some typos

- .github/workflows/rust.yml
- crates/freya/src/_docs/animating.rs
- crates/freya/src/_docs/hot_reload.rs
- crates/freya/src/_docs/theming.rs
- crates/freya/src/launch.rs
- crates/freya/src/lib.rs
- examples/pointer.rs
This PR includes examples when testing and adds doctests **only for the `freya` crate** (which tests the book right now). That's because there's 114 failing doctests in other crates which I wasn't feeling like fixing, but I think imports are the source of most errors, so it shouldn't be that hard. I can do it, but I wouldn't mind if someone else did it.
There were some errors which I fixed to make all new tests pass, and not all of them were just about importing stuff. That's why I strongly think this PR should be merged, along with fixing all errors in the other docs and testing those too.
> Add example and doc tests to workflow

- book/src/SUMMARY.md
- book/src/guides/publishing.md
This finishes the empty publishing chapter. `cargo-packager` is the tool used, but alternatives are mentioned.
> Create publishing chapter

- crates/components/src/table.rs
I was a bit surprised to see "Down" and "Up" for order rather than "Ascending" and "Descending", so this fixes that (doesn't rename the variants, just adds docs). Also adds a note that the table `order_direction` prop is only visual.
> Improve `OrderDirection` docs

- crates/components/src/scroll_views/scroll_bar.rs
- crates/components/src/scroll_views/scroll_view.rs
- crates/components/src/scroll_views/virtual_scroll_view.rs
- crates/hooks/src/theming/dark.rs
- crates/hooks/src/theming/light.rs
- crates/hooks/src/theming/mod.rs
Reverts some changes from https://github.com/marc2332/freya/pull/425
> chore: `ScrollBar` offset props must be component props not part of a theme

- crates/hooks/src/rope_editor.rs
- crates/hooks/src/text_editor.rs
- Don't remove the highlights when pressing Alt or Ctrl alone
- Jump to the begining of the line when pressing Up and having reached the first line
- Jump to the end of the line when pressing Down and having reached the last line
- Don't mark as the highlights has changed if there is anything selected at all
> feat: Text Editor improvements

- crates/hooks/src/text_editor.rs
Prevent cursor to jump to the next line when there are no more lines, in  `TextEditor`
> fix: Prevent cursor to jump to the next line when there are no more lines, in  `TextEditor`

- crates/hooks/src/theming/mod.rs
I tend to make trailing commas required for standardization but public macros should be more permissive especially since the error without the trailing comma is not very self explanatory.
> Remove required trailing comma in `theme_with` macro

- book/src/guides/layout.md
- crates/elements/src/_docs/attributes/margin.md
- crates/elements/src/_docs/attributes/padding.md
- crates/state/src/values/gaps.rs
- crates/state/tests/parse_gaps.rs
- examples/paddings.rs
Example: `"2 15 25" // 2 in top, 15 in left and right, and 25 in bottom`
> feat: Support individual vertical gaps but shared horizontal gaps

- crates/hooks/src/use_node.rs
- crates/state/src/custom_attributes.rs
Depends on https://github.com/marc2332/freya/pull/346
Using `tokio::watch` is more suitable as there is only one listener and one sender
> feat: Improved node reference listener

- crates/components/src/gesture_area.rs
- crates/core/src/layout/skia_measurer.rs
- crates/renderer/src/elements/label.rs
- crates/torin/benches/bench.rs
- crates/torin/examples/demo.rs
- crates/torin/src/custom_measurer.rs
- crates/torin/src/measure.rs
- crates/torin/src/test_utils.rs
Depends on https://github.com/marc2332/freya/pull/346
> feat: Simplify text measuring and rendering

- crates/testing/src/test_node.rs
- crates/testing/src/test_utils.rs
- crates/testing/tests/test.rs
Example:
```rs
#[tokio::test]
async fn match_by_text() {
rsx!(
label {
"Hello, World!"
}
rect {
label {
"Hello, Rust!"
}
}
)
}
let mut utils = launch_test(app);
assert_eq!(
utils.root().get_by_text("Hello, World!").unwrap().text(),
Some("Hello, World!")
);
assert!(utils.root().get_by_text("Blabla").is_none());
assert_eq!(
utils.root().get_by_text("Hello, Rust!").unwrap().text(),
Some("Hello, Rust!")
);
}
```
> feat: Support querying nodes by a matching text in `freya-testing`

- crates/state/src/font_style.rs
- crates/state/src/layout.rs
- crates/torin/src/torin.rs
Depends on https://github.com/marc2332/freya/pull/564
> fix: Adjust root offsets for incremental measurements

- crates/state/src/layout.rs
Reverts https://github.com/marc2332/freya/commit/a9c52733f411fc177aa88c10a2e3220ea6ec8bcc
> fix: Bring back node id layout check

- crates/core/src/dom/dom_adapter.rs
- crates/core/tests/compatible_elements.rs
- crates/torin/src/measure.rs
Closes https://github.com/marc2332/freya/issues/588
> feat: Ignore invalid nodes

- crates/common/src/event_messages.rs
- crates/components/src/lib.rs
- crates/components/src/window_drag_area.rs
- crates/hooks/src/use_platform.rs
- crates/renderer/src/event_loop.rs
- examples/window_drag_area.rs
Closes https://github.com/marc2332/freya/issues/262
> feat: Add window drag area

- crates/common/src/event_messages.rs
- crates/components/src/window_drag_area.rs
- crates/hooks/src/use_platform.rs
- crates/renderer/src/event_loop.rs
Closes https://github.com/marc2332/freya/issues/612
Example:
```rs
let platform = use_platform();
rsx!(
Button {
onclick: move |_| platform.exit(),
label { "Close" }
}
)
}
```
> feat: Close app with `use_platform`

- crates/components/src/window_drag_area.rs
When the `WindowDragArea` component received a non-left click, the drag area would become disabled, even when receiving standard right click events.
Fixed by adding a check in the `onmousedown` function within the component.
> fix: `WindowDragArea` component hanging on non-left click.

- crates/components/src/input.rs
- crates/engine/src/skia.rs
- crates/hooks/src/editor_history.rs
- crates/hooks/src/rope_editor.rs
- crates/hooks/src/text_editor.rs
- crates/hooks/src/use_editable.rs
- crates/hooks/tests/use_editable.rs
- crates/testing/src/launch.rs
- examples/cloned_editor.rs
- examples/simple_editor.rs
Closes https://github.com/marc2332/freya/issues/494
> feat: Improved special text editing support

- crates/core/src/dom/doms.rs
- crates/core/src/dom/paragraph_utils.rs
- crates/hooks/src/use_editable.rs
- examples/simple_editor.rs
Take the cursor position and selections the moment it is measured instead of received by `use_editable` to avoid unnecessary measurements
Closes https://github.com/marc2332/freya/issues/623
> fix: Fix performance dropping rapidly after selecting a text for some time

- crates/common/src/event_messages.rs
- crates/common/src/paragraphs.rs
- crates/core/src/dom/doms.rs
- crates/core/src/dom/paragraph_utils.rs
- crates/core/src/layout/layout_measurer.rs
- crates/hooks/src/rope_editor.rs
- crates/hooks/src/text_editor.rs
- crates/hooks/src/use_editable.rs
- crates/renderer/src/app.rs
- crates/renderer/src/event_loop.rs
- crates/state/src/custom_attributes.rs
- crates/testing/src/test_handler.rs
Fixes https://github.com/marc2332/freya/issues/623
> feat: Revamp internal text selection

- crates/hooks/src/rope_editor.rs
- crates/hooks/src/text_editor.rs
- crates/hooks/src/use_editable.rs
- crates/hooks/tests/use_editable.rs
- examples/floating_editors.rs
- examples/simple_editor.rs
> refactor: Use single position cursor

- crates/hooks/src/use_asset_cacher.rs
- crates/hooks/src/use_init_native_platform.rs
Closes https://github.com/marc2332/freya/issues/666
This PR modifies under what Scope the cached assets are stored, previously they were stored under the first Scope that called use_asset_cacher, this is obviously a problem if that Scope is dropped. Therefore, this PR will make all assets be stored under The ROOT scope.
> fix: Store cached assets in Root Scope

- crates/hooks/src/rope_editor.rs
- crates/hooks/src/text_editor.rs
- crates/hooks/src/use_editable.rs
- examples/simple_editor.rs
Closes https://github.com/marc2332/freya/issues/662
> feat: Optionally allow inserting tabs as spaces

- crates/core/src/dom/dom_adapter.rs
- crates/core/src/dom/doms.rs
- crates/core/src/dom/mutations_writer.rs
- crates/core/src/layout/layout_measurer.rs
- crates/core/src/layout/skia_measurer.rs
- crates/renderer/src/app.rs
- crates/renderer/src/elements/paragraph.rs
- crates/renderer/src/elements/rect.rs
- crates/renderer/src/render.rs
- crates/state/src/font_style.rs
- crates/state/src/layout.rs
- crates/state/src/style.rs
- crates/torin/src/node.rs
- crates/torin/src/values/position.rs
Closes https://github.com/marc2332/freya/issues/270
depends on https://github.com/marc2332/freya/pull/598
WIP
> feat: React to scale factor changes

- crates/components/src/graph.rs
- crates/hooks/src/use_canvas.rs
- examples/render_canvas.rs
- examples/shader.rs
Closes https://github.com/marc2332/freya/issues/692
> feat: Signal-based reactivity for `use_canvas`

- .gitignore
- Cargo.toml
- crates/engine/src/mocked.rs
- crates/engine/src/skia.rs
- crates/testing/src/launch.rs
- crates/testing/src/test_handler.rs
- examples/canvas_snapshot.rs
Closes https://github.com/marc2332/freya/issues/702
> feat: Canvas snapshots for `freya-testing`

- crates/core/src/dom/mutations_writer.rs
Closes https://github.com/marc2332/freya/issues/602
> fix: Skip DOM Nodes loaded in the same mutations run

- crates/hooks/src/use_animation.rs
This makes it easier to make custom hooks with use_animation
example:
```rs
fn use_custom_animation(origin: &'static str, target: &'static str) -> UseAnimator<ReadAnimatedValue> {
use_animation(|ctx| {
ctx.with(
AnimColor::new(origin, target)
.time(100)
.ease(Ease::Out)
)
})
}
```
> feat: Simplify return type of `use_animation`

- crates/freya/src/launch.rs
- crates/renderer/src/config.rs
- crates/renderer/src/window_state.rs
- examples/cloned_editor.rs
- examples/custom_font.rs
- examples/frameless_window.rs
- examples/installer/src/main.rs
- examples/launch_setup.rs
- examples/performance_overlay_plugin.rs
- examples/plugin.rs
- examples/shader_editor.rs
- examples/window_icon.rs
Closes https://github.com/marc2332/freya/issues/756
It will not be allowed anymore to pass individual values for window sizing as it can lead to unexpected behaviors.
> fix: Require to pass both the width and height for window size at once when desired

- crates/renderer/src/renderer.rs
Winit only emits mouseover events when (case 1) the cursor is inside the window or (case 2) when the cursor is outside the window, but a click event was initiated inside the window. 
This PR fixes a bug where the left mouseover was being emitted even in case 2.
> fix: Only send left mouseover event when not clicking the mouse

- Cargo.toml
- crates/freya/Cargo.toml
- crates/freya/src/launch.rs
Closes https://github.com/marc2332/freya/issues/490
> feat: Add `performance-overlay` feature to `freya` crate

- Cargo.toml
- crates/components/src/graph.rs
- crates/core/src/elements/rect.rs
- crates/hooks/src/use_canvas.rs
- crates/renderer/src/window_state.rs
- crates/state/src/custom_attributes.rs
- examples/opengl_rtt.rs
- examples/render_canvas.rs
- examples/shader.rs
- examples/shader_editor.rs
- wraps parameters of CanvasRunner to struct, just in case more rendering information will be passed in future
- adds simple opengl_rtt example:
- messing with raw opengl to render triangle
- renders to texture
- using raw opengl texture to draw on skia canvas
> Add opengl_rtt example.

- crates/components/src/dropdown.rs
- crates/components/src/link.rs
- crates/components/src/scroll_views/scroll_view.rs
- crates/components/src/sidebar.rs
- crates/components/src/switch.rs
- crates/core/src/dom/dom_adapter.rs
- crates/elements/src/_docs/attributes/spacing.md
- crates/elements/src/definitions.rs
- crates/hooks/src/theming/dark.rs
- crates/hooks/src/theming/light.rs
- crates/hooks/src/theming/mod.rs
- crates/native-core/src/attributes.rs
- crates/state/src/layout.rs
- crates/torin/src/measure.rs
- crates/torin/src/node.rs
- crates/torin/tests/spacing.rs
- examples/counter.rs
- examples/popup.rs
- examples/spacing.rs
Closes https://github.com/marc2332/freya/issues/829
> feat: `spacing` attribute

- .gitignore
- crates/elements/src/_docs/attributes/main_align_cross_align.md
- examples/documents_editor.rs
> docs: Documents editor example

- crates/components/src/drag_drop.rs
- crates/core/src/events/events_measurer.rs
- crates/core/src/events/nodes_state.rs
- crates/elements/src/_docs/events/mouseup.md
- crates/elements/src/definitions.rs
- crates/native-core/src/events.rs
- crates/renderer/src/app.rs
- crates/renderer/src/renderer.rs
- crates/testing/src/test_handler.rs
- examples/counter.rs
Closes https://github.com/marc2332/freya/issues/849
Click events will only be emitted to elements that were previously pressed down (no need to register a mousedown event). Mouse leave events wont need a mouseenter or mouseevents to be registered in the nodes. Added a new `mouseup` event that behaves like the old onclick
This also cleans up a bit the internals.
I also made an exception for `freya-testing` so it can emit click events without the need of sending mousedown events before.
> feat: Improved nodes events states

- crates/core/src/accessibility/tree.rs
- crates/engine/src/mocked.rs
This PR fills out the following AccessKit node properties based on known node state:
- `transform` (rotation)
- `clips_children` (overflow)
- `foreground_color`, `background_color`
- `is_line_breaking_object` (has block-level layout)
- `font_size`
- `font_family` (only for nodes changing the family, child nodes already inherit)
- `bold`
- `text_align`
- `text_direction` (always LTR currently)
- `italic` (for `FontSlant` `Italic` and Oblique)
- `text_decoration`
- `underline`
- `overline`
- `strikethrough`
It also adjusts the way that the `Focus` action is applied for focusable nodes. This is the previous code:
```rs
// Set focusable action
if node_accessibility.focusable {
builder.add_action(Action::Focus);
} else {
builder.add_action(Action::Default); …
```
> feat: infer accesskit properties from node state

- crates/components/src/scroll_views/mod.rs
- crates/components/src/scroll_views/scroll_view.rs
- crates/components/src/scroll_views/virtual_scroll_view.rs
- crates/components/src/sidebar.rs
- crates/devtools/src/tabs/layout.rs
- crates/devtools/src/tabs/style.rs
- crates/devtools/src/tabs/tree.rs
- crates/hooks/src/theming/dark.rs
- crates/hooks/src/theming/light.rs
- crates/hooks/src/theming/mod.rs
- examples/accordion.rs
- examples/cloned_editor.rs
- examples/controlled_scroll.rs
- examples/material_design_app.rs
- examples/paragraph.rs
- examples/scroll.rs
- examples/simple_editor.rs
- examples/ui.rs
Both ScrollView and VirtualScrollView no longer use a theme for the width, height, padding and spacing. And now, both of them can shrink to the size of its children size in the axis direction when that is "auto". So for example you can make a vertical ScrollView shrink to its inner children size by specifying a `width: "auto"`
Closes https://github.com/marc2332/freya/issues/857
> feat: Ergonomic improvements in ScrollView

- crates/torin/src/measure.rs
- crates/torin/src/node.rs
- crates/torin/tests/alignment.rs
Completely ignore absolute nodes when measuring the required spacing between children and also for axis alignments
> fix(torin): Ignore absolute nodes for spacing and alignments

- crates/components/src/link.rs
- crates/components/src/tooltip.rs
- crates/core/src/render/skia_measurer.rs
- examples/switch_theme.rs
- examples/tooltip.rs
Closes https://github.com/marc2332/freya/issues/581
> feat: `TooltipContainer`

- crates/state/src/values/size.rs
- crates/state/tests/parse_size.rs
- crates/torin/src/values/size.rs
- crates/torin/tests/size.rs
Closes https://github.com/marc2332/freya/issues/906
> feat: Support RootPercentage in `calc()`

- crates/components/src/slider.rs
- examples/floating_editors.rs
- examples/opacity.rs
- examples/opengl_rtt.rs
- examples/progress_bar.rs
- examples/switch_theme.rs
- examples/text.rs
Closes https://github.com/marc2332/freya/issues/908
> feat: Vertical `direction` for `Slider`

- crates/renderer/src/window_state.rs
Context https://github.com/marc2332/freya/discussions/929
> refactor: Remove `accesskit` window rendering workaround

- Cargo.toml
- crates/freya/Cargo.toml
- crates/renderer/Cargo.toml
- crates/renderer/src/app.rs
- crates/renderer/src/renderer.rs
Closes https://github.com/marc2332/freya/issues/57
> feat: Custom scale factor shortcuts

- crates/components/src/button.rs
- crates/components/src/tooltip.rs
- crates/core/src/elements/paragraph.rs
- crates/core/src/node.rs
- crates/core/src/render/skia_measurer.rs
- crates/devtools/src/tabs/style.rs
- crates/hooks/tests/use_editable.rs
- crates/state/src/font_style.rs
- examples/input.rs
Otherwise some characters might get cut.
> fix: Use the real text height for layout

- crates/renderer/src/config.rs
- crates/renderer/src/window_state.rs
Also fixes a regression of https://github.com/marc2332/freya/pull/930
> feat: `LaunchConfig::with_visible`

- crates/native-core-macro/src/lib.rs
- crates/native-core/Cargo.toml
- crates/native-core/src/lib.rs
- crates/native-core/src/passes.rs
Closes https://github.com/marc2332/freya/issues/993
> refactor: Remove `anymap`

- crates/core/src/elements/paragraph.rs
- crates/core/src/render/skia_measurer.rs
- crates/core/src/render/utils/label.rs
- crates/core/src/render/utils/paragraph.rs
Prevents text with non-start alignment like the new upcoming Clock example from using an incorrect layout and thus causing issues with incremental rendering
> fix: Use paragraph's full width if text align is non-start

- crates/torin/src/lib.rs
- crates/torin/src/values/size.rs
- crates/torin/tests/size.rs
Reverts marc2332/freya#1006
This causes incosistent behavior when using e.g percentages:
```rs
rsx!(
rect {
width: "calc(50%)", // Not expected
height: "50%",
background: "red"
}
rect {
width: "50%", // Expected
height: "50%",
background: "blue"
}
)
```
> Revert "Fix scale factor behavior in `calc()`"

- crates/core/src/dom/mutations_writer.rs
- crates/core/src/layout.rs
- crates/core/src/render/compositor.rs
- crates/core/tests/nodes_reorder.rs
- crates/native-core/src/dioxus.rs
- crates/native-core/src/tree.rs
- crates/torin/src/measure.rs
- crates/torin/src/torin.rs
- crates/torin/tests/other.rs
These two code blocksd didn't work correctly before:
```rust
#![cfg_attr(
all(not(debug_assertions), target_os = "windows"),
windows_subsystem = "windows"
)]
use freya::prelude::*;
use rand::Rng;
fn main() {
launch_with_props(app, "Counter", (400.0, 350.0));
}
let mut data = use_signal(Vec::<usize>::new);
rsx!(
rect {
height: "100%",
width: "100%",
Button {
onclick: move |_| {
let mut item = data.write().remove(0);
data.write().push(item);
},
label {
"Move"
}
}
Button {
onclick: move |_| {
let mut rng = rand::thread_rng();
data.write().insert(0,rng.gen());
},
label {
"Add"
}
}
for d in data.read().iter() {
label {
key: "{d}",
height: "20",
"{d}"
}
}
}
)
}
```
```rust
#![cfg_attr(
all(not(debug_assertions), target_os = "windows"),
windows_subsystem = "windows"
)]
use …
```
> fix: Handle reordedering of keyed children

- book/src/differences_with_dioxus.md
I just stumbled upon freya coming from Dioxus and noticed a couple typos in the book. This should improve this section a bit.
> docs: fix typos and improve text in "Differences with Dioxus" section

- crates/engine/src/mocked.rs
Fixes https://docs.rs/crate/freya/0.3.0-rc.0/builds/1603660
> fix: Add missing `Data` to `[u8]` deref

- crates/components/src/accordion.rs
- crates/components/src/animated_position.rs
- crates/components/src/loader.rs
- crates/components/src/overflowed_content.rs
- crates/components/src/snackbar.rs
- crates/components/src/switch.rs
- crates/hooks/src/lib.rs
- crates/hooks/src/use_animation.rs
- crates/hooks/tests/use_animation.rs
- examples/animated_sidebar.rs
- examples/animated_tabs.rs
- examples/animated_virtual_scroll_view.rs
- examples/animation.rs
- examples/performance_overlay_plugin.rs
- examples/progress_bar.rs
- examples/snackbar.rs
- examples/speedometer.rs
Internally, `use_animation` now only animates 1 value, although because the trait `AnimatedValue` is now implemented for tuples with up to 18 items you can still group multiple values
> feat: Type safety for `use_animation`

- crates/core/src/render/skia_measurer.rs
- crates/torin/benches/bench.rs
- crates/torin/examples/demo.rs
- crates/torin/src/custom_measurer.rs
- crates/torin/src/dom_adapter.rs
- crates/torin/src/lib.rs
- crates/torin/src/sendanymap.rs
- crates/torin/src/test_utils.rs
Also put `NoopMeasurer` in torin.
> fix: Add custom SendAnyMap for torin to not depend on freya-native-core

- crates/components/src/overflowed_content.rs
Sometimes it fails in the CI, probably because of timers
> fix: Poll one more time the overflowed content test

- crates/hooks/src/use_animation.rs
This could have technically leak memory as long as the scope was alive and the animation runner might have rerun multiple times (this will only happens if the manual dependencies or read signals, change)
> fix: Manually drop previous animated values when the run callback reruns

- crates/freya/src/lib.rs
- crates/hooks/src/use_focus.rs
- crates/hooks/src/use_platform.rs
- examples/delegated_focus.rs
This allows to move the focus logic up to a global state
> feat: Delegated focus

- crates/components/src/button.rs
- crates/components/src/checkbox.rs
- crates/components/src/dropdown.rs
- crates/components/src/radio.rs
- crates/components/src/slider.rs
- crates/components/src/switch.rs
- crates/components/src/tabs.rs
- crates/components/src/tile.rs
- crates/hooks/src/use_focus.rs
Closes https://github.com/marc2332/freya/issues/883
Stop using `globalkeydown` for Switch and Button, and now `validate_keydown` will also fire when Space is pressed.
> refactor: Improved `UseFocus::validate_keydown`

- crates/components/src/drag_drop.rs
- crates/components/src/popup.rs
- crates/core/src/elements/utils.rs
- crates/core/src/states/layout.rs
- crates/torin/src/measure.rs
- crates/torin/src/values/position.rs
- examples/todo.rs
https://github.com/user-attachments/assets/c56186c9-6e46-4a9a-b1ef-92b786aeea7b
- DragZone will only dragging for the left mouse button
- more conservative compositor caching area inflation
- Made the Popup be global positioned
- Fixed that that the global position was not using the `position_top` and the other position attributes
> feat: `todo.rs` example and some fixes

- crates/components/src/graph.rs
Closes https://github.com/marc2332/freya/issues/691
> fix: Scale `Graph` according to the scale factor

- crates/core/src/elements/image.rs
Partial revert of https://github.com/marc2332/freya/commit/9226b655c3ee5a7f8908b34bd7a60066550d194f#diff-c0a88ed9a55d3f60cdd03150049f2cf5c4eb26149de400c98c4a58320c970198
This was affecting the aspect ratio feature
> fix: Revert image clipping removal

- crates/winit/src/app.rs
- crates/winit/src/renderer.rs
This prevents a small blink on the currently focused element when the user presses Tab or Shift Tab to focus the next element
> fix: Update the navigation mode after the accessibility update

- crates/hooks/src/use_animation/anim_color.rs
- crates/hooks/src/use_animation/anim_num.rs
- crates/hooks/src/use_animation/animated_value.rs
- examples/animated_tabs.rs
Some animated values were never reaching their destination even though their ease functions were given the right params, so I made it return the destination once the last index is reached
> fix: Prevent animations stalling

- crates/components/src/popup.rs
- crates/core/src/events/nodes_state.rs
- crates/native-core/src/events.rs
Only those nodes previously marked as `pressed` (mousedown, pointerdown, etc) are allowed to have emitted `release` (click, pointerup, etc) events on them.
> fix: Only send release events on pressed nodes

- crates/winit/src/app.rs
- crates/winit/src/devtools.rs
This fixes a small bug where the devtools nodes vec was empty on certain updates where there was a repaint and relayout, the fact that where was a relayout but the layout had not been remeasured yet means that the nodes were not in sync yet
> fix: Only update devtools on repaint or relayout, but not both

- crates/core/src/events/events_measurer.rs
- crates/native-core/src/events.rs
Closes https://github.com/marc2332/freya/issues/1167
It doesnt make sense to create global events based on dom events, as these might or not happen, neither it makes sense to also consider collateral events as there is no collateral event that also has a global variant, for global events, instead it is as easy as using the platform events and their derived events to create global events
> fix: Only create global events based on the platform derived events

- crates/hooks/src/text_editor.rs
- crates/hooks/tests/use_editable.rs
Closes https://github.com/marc2332/freya/issues/1177
> fix: Avoid overflow on keyboard navigation in empty lines of text

- crates/components/src/scroll_views/virtual_scroll_view.rs
Removes the empty bit at the end of a `VirtualScrollView` component to match with a regular `ScrollView` component.
Video showing the empty bit:
https://github.com/user-attachments/assets/29efdfb3-54c2-4a5b-bc09-3c9b0f09cfd8
The changes related to imports are caused by the code formatter in my code editor.
> fix: remove unnecessary empty section at the end of VirtualScrollView component

- examples/conditional_rendering.rs
Conditional rendering is better than a router when specific components need to be rendered based on something, e.g. a state (at least in my opinion), so I added an example for it.
> docs: add example for conditional rendering

- crates/core/src/values/color.rs
- crates/core/tests/parse_color.rs
Example code:
```rust
#![cfg_attr(
all(not(debug_assertions), target_os = "windows"),
windows_subsystem = "windows"
)]
use freya::prelude::*;
const CUSTOM_THEME: Theme = Theme {
button: ButtonTheme {
// Black HEX color with transparency
background: Cow::Borrowed("#0000003C"),
hover_background: Cow::Borrowed("#00000000"),
border_fill: Cow::Borrowed("#00000000"),
focus_border_fill: Cow::Borrowed("#00000000"),
font_theme: FontTheme {
color: Cow::Borrowed("#000000"),
},
..LIGHT_THEME.button
},
..LIGHT_THEME
};
fn main() {
launch(app);
}
rsx!(
ThemeProvider {
theme: CUSTOM_THEME,
rect {
width: "100%",
height: "100%",
main_align: "center",
cross_align: "center",
Button {
label {
"Cancel"
}
}
}
}
)
}
```
Result:
> HEX transparency

- crates/core/src/animation_clock.rs
- crates/core/src/dom/doms.rs
- crates/core/src/lib.rs
- crates/freya/src/lib.rs
- crates/freya/src/plugins/performance_overlay.rs
- crates/hooks/src/use_animation/hook.rs
- crates/testing/src/test_handler.rs
- crates/winit/Cargo.toml
- crates/winit/src/app.rs
- crates/winit/src/renderer.rs
Closes https://github.com/marc2332/freya/issues/940
Adds a new debug-only shortcut to slow down or speed up animations
- Slow down: Linux/Windows = `Ctrl Alt -`, Mac = `Super Alt -`
- Speed up: Linux/Windows = `Ctrl Alt +`, Mac = `Super Alt +`
> feat: Add `AnimationClock` to universally slow down or speed up animations

- crates/components/src/native_container.rs
- crates/hooks/src/use_focus.rs
- crates/hooks/src/use_platform.rs
- examples/delegated_focus.rs
`PlatformSender` makes it possible to send events from other threads
Added because of https://github.com/marc2332/freya/discussions/1237
Example:
```rust
let platform = use_platform();
use_hook(|| {
let sender = platform.sender();
std::thread::spawn(move || loop {
std::thread::sleep(Duration::from_millis(500));
sender.with_window(|window| {
println!("{:?}", window.is_minimized());
});
});
});
rsx!(
rect { }
)
}
```
> feat: `UsePlatform::sender`

- crates/components/src/resizable_container.rs
- crates/components/src/scroll_views/scroll_view.rs
- crates/core/src/events/events_measurer.rs
- crates/core/src/events/handler.rs
- crates/core/src/events/nodes_state.rs
- crates/core/src/types.rs
- crates/native-core/src/events.rs
- crates/testing/src/test_handler.rs
- crates/winit/src/app.rs
Continues the work of https://github.com/marc2332/freya/pull/1215
> fix: Only discard cancelled events in the same run

- crates/devtools/src/lib.rs
- crates/devtools/src/tabs/layout.rs
- crates/devtools/src/tabs/style.rs
- crates/devtools/src/tabs/tree.rs
- crates/native-core-macro/src/lib.rs
- crates/native-core/Cargo.toml
- crates/native-core/src/lib.rs
- crates/native-core/src/node_id.rs
- crates/native-core/src/real_dom.rs
- crates/native-core/src/tree.rs
- crates/torin/Cargo.toml
- crates/torin/src/dom_adapter.rs
Make `freya-native-core`'s NodeId a wrapper type rather than type alias
> refactor: Make `freya-native-core`'s NodeId a wrapper type rather than type alias

- crates/core/src/elements/rect.rs
- crates/core/src/elements/utils.rs
- crates/core/src/render/compositor.rs
Mark a whole element area as invalidated in the compositor if it uses blur, as skia blur does not work well when the canvas clip is smaller than blurred area
> fix: Mark a whole element area as invalidated if using blur

- crates/hooks/src/use_animation/hook.rs
This way I can read the conf while the animated value is being mutated
> fix: Separate animated value and conf in `use_animation`

- Cargo.toml
- crates/components/src/scroll_views/virtual_scroll_view.rs
- crates/devtools/Cargo.toml
- examples/split_editors.rs
Showcases how to manage N amount of editors, all stored in the same global state and yet be able to make granular updates and subscriptions.
> docs: Split editor example
