examples/drawer.rs
this pr enables closing the drawer when clicking outside of it
=> feat: click outside drawer

components/src/scroll_view.rs, examples/scroll.rs, layout/src/lib.rs
This PR adds support for horizontal Scrollbars:
=> feat: Support horizontal Scrollbars

Cargo.lock, examples/paragraph.rs, examples/text.rs, layout/Cargo.toml, layout/src/lib.rs, layout/tests/layouts.rs, renderer/src/renderer.rs, renderer/src/work_loop.rs, state/src/node.rs
Labels will now fit it's size according to its text, I accomplished this by using Skia's Paragraph. WIP
Example:
=> feat: Labels will now fit it's size according to it's text

Cargo.lock, Cargo.toml, examples/editor.rs, examples/massive.rs, layers/Cargo.toml, layers/src/lib.rs, layout-common/src/node_area.rs, renderer/Cargo.toml, renderer/src/events_processor.rs, renderer/src/lib.rs, renderer/src/renderer.rs, renderer/src/work_loop.rs
=> refactor: Some optimizations

Cargo.lock, Cargo.toml, components/Cargo.toml, components/src/button.rs, components/src/input.rs, components/src/lib.rs, components/src/scroll_views/scroll_view.rs, components/src/scroll_views/virtual_scroll_view.rs, components/src/slider.rs, components/src/switch.rs, examples/editor.rs, examples/showcase.rs, examples/theme.rs, freya/Cargo.toml, freya/src/devtools.rs, hooks/src/lib.rs, hooks/src/use_theme.rs
Closes https://github.com/marc2332/freya/issues/38
=> feat: Scoped themes

components/src/scroll_views/mod.rs, components/src/scroll_views/scroll_view.rs, components/src/scroll_views/virtual_scroll_view.rs, examples/text.rs
Closes https://github.com/marc2332/freya/issues/15
=> fix: Fixed scroll views overflow

Cargo.lock, Cargo.toml, common/Cargo.toml, components/Cargo.toml, elements/Cargo.toml, freya/Cargo.toml, hooks/Cargo.toml, layout/Cargo.toml, processor/Cargo.toml, readme.md, renderer/Cargo.toml, state/Cargo.toml, testing/Cargo.toml
This updates Freya's pinned Dioxus commit to the latest on their master branch.
=> feat: Updated to 1b597f

Cargo.lock, Cargo.toml, common/Cargo.toml, components/Cargo.toml, elements/Cargo.toml, freya/Cargo.toml, hooks/Cargo.toml, layout/Cargo.toml, layout/src/lib.rs, processor/Cargo.toml, processor/src/lib.rs, readme.md, renderer/Cargo.toml, state/Cargo.toml, state/src/lib.rs, testing/Cargo.toml
- Some performance boost in the layout library
- Updated Dioxus because of https://github.com/DioxusLabs/dioxus/pull/802
=> feat: Performance boost and updated Dioxus

components/src/dropdown.rs, components/src/lib.rs, elements/src/lib.rs, examples/dropdown.rs, hooks/src/use_theme.rs, processor/src/events.rs, processor/src/lib.rs
=> feat: Dropdown component & onglobalclick event

freya/src/devtools.rs
- Devtools now uses a VirtualScrollView
- Improved design of the selected node
=> feat: VirtualScrollView in devtools and improved design

docs/src/setup.md
It seems macOS doesn't require any setup. Maybe this can reflect to the doc.
=> Update macOS setup description

Cargo.toml, examples/camera.rs, freya/Cargo.toml, hooks/Cargo.toml, hooks/src/lib.rs
Closes https://github.com/marc2332/freya/issues/70
=> Feat: `use_camera` feature

codecov.yml
=> feat: fail_ci_if_error: false

components/src/scroll_views/scroll_view.rs, components/src/scroll_views/virtual_scroll_view.rs, elements/src/events_data/wheel.rs
=> feat: Improved horizontal scrolling

devtools/src/lib.rs, hooks/src/use_animation.rs, hooks/src/use_focus.rs, hooks/tests/use_editable.rs, testing/Cargo.toml, testing/src/lib.rs, testing/tests/test.rs
- Removed unnecessary async
- Removed unnecessary `Arc<Mutex<T>>`
- Reused code
- Few comments
=> feat: Refactor freya-testing

common/src/layout.rs, core/src/events.rs, core/src/lib.rs, dom/src/dom.rs, freya/src/lib.rs, layout/src/lib.rs, layout/tests/layouts.rs, renderer/src/app.rs, renderer/src/window.rs, state/src/font_style.rs, state/src/scroll.rs, state/src/size.rs, state/src/style.rs, state/tests/parse_paddings.rs, state/tests/parse_size.rs, testing/src/lib.rs
Closes https://github.com/marc2332/freya/issues/1
It scales the layout with the window's scale factor
=> feat: Adaptive layout scale

layout/src/lib.rs
Closes https://github.com/marc2332/freya/issues/150
=> feat: Skip layout of paragraph inner text nodes

components/src/gesture_area.rs, hooks/src/use_animation.rs, hooks/src/use_focus.rs, hooks/src/use_node.rs, hooks/tests/use_editable.rs, testing/src/lib.rs, testing/tests/test.rs
Closes https://github.com/marc2332/freya/issues/153
=> feat: Simplify testing utilities

Cargo.lock, Cargo.toml, components/src/canvas.rs, components/src/lib.rs, elements/src/elements.rs, examples/render.rs, examples/render_canvas.rs, hooks/Cargo.toml, hooks/src/lib.rs, hooks/src/use_canvas.rs, renderer/src/elements/rect_container.rs, state/src/custom_attributes.rs, state/src/references.rs, state/src/transform.rs
Closes https://github.com/marc2332/freya/issues/101
=> feat: Raw canvas access 

Cargo.lock, common/Cargo.toml, common/src/event_messages.rs, hooks/src/use_editable.rs, layout/Cargo.toml, layout/src/layers.rs, layout/src/lib.rs, renderer/Cargo.toml, renderer/src/app.rs, renderer/src/lib.rs, state/Cargo.toml, state/src/custom_attributes.rs, state/src/font_style.rs
=> fat: Measure text elements data independently from layout

components/src/scroll_views/mod.rs, renderer/src/lib.rs
Closes https://github.com/marc2332/freya/issues/164
=> fix: Leave MouseScrollDelta::PixelDelta raw

examples/animation.rs, examples/canvas.rs, examples/cloned_editor.rs, examples/editor.rs, examples/floating_window.rs, examples/mouse_trace.rs, examples/rotate.rs, examples/showcase.rs, examples/touch.rs, freya/src/launch.rs, renderer/src/lib.rs, renderer/src/window.rs, renderer/src/window_config.rs
Closes https://github.com/marc2332/freya/issues/168
=> fix: Use LogicalSize for Window creation and changed default size

freya/src/launch.rs, renderer/src/window.rs, renderer/src/window_config.rs
Closes https://github.com/marc2332/freya/issues/45
=> feat: Specify a custom window background

Cargo.lock, Cargo.toml, renderer/Cargo.toml
Closes https://github.com/marc2332/freya/issues/173
=> feat: Update to skia-safe v0.62.0

components/src/dropdown.rs
Closes https://github.com/marc2332/freya/issues/166
=> feat: Hover effect in dropdown items

.github/workflows/rust.yml, Cargo.lock, components/src/drag_drop.rs, components/src/gesture_area.rs, core/Cargo.toml, core/src/events.rs, core/src/lib.rs, core/tests/events.rs, elements/src/elements.rs, elements/src/events.rs, elements/src/events/pointer.rs, examples/pointer.rs, hooks/src/use_animation.rs, hooks/src/use_focus.rs, hooks/tests/use_editable.rs, renderer/src/lib.rs, testing/tests/test.rs
Closes https://github.com/marc2332/freya/issues/201
=> feat: Pointer events

book/src/index.md
Fixes a typo and some minor grammar issues.
=> docs: misc introduction fixes

core/src/events.rs
=> fix: Stack ontouchmove

torin/src/torin.rs, torin/src/values/size.rs
Closes https://github.com/marc2332/freya/issues/279
=> fix: Proper min max sizing

crates/components/src/cursor_area.rs
Closes https://github.com/marc2332/freya/issues/278
=> feat: Set cursor to default on unmount in `CursorArea`

crates/dom/src/dom_adapter.rs
Closes https://github.com/marc2332/freya/issues/302
=> fix: Filter invalid children in `DioxusDOMAdapter::children_of`

crates/core/src/layout.rs, crates/dom/src/dom.rs, crates/dom/src/dom_adapter.rs, crates/torin/benches/bench.rs, crates/torin/src/dom_adapter.rs, crates/torin/src/torin.rs, crates/torin/tests/test.rs
Closes https://github.com/marc2332/freya/issues/304
=> feat: Cache nodes validations

book/src/setup.md
Add Arch Linux setup packages
PS: Sorry for the delay :grin:
=> docs: Arch Linux setup instructions

crates/engine/src/skia.rs, crates/hooks/src/use_animation.rs, crates/hooks/src/use_animation_transition.rs, crates/renderer/src/window.rs
=> feat: Avoid extra animations overhead

Cargo.toml, README.md, book/src/guides/getting_started.md
- Debug: from 484 deps to 466
- Release: from 534 deps to 516
=> chore: Disable web dioxus features

book/src/guides/layout.md, crates/state/src/values/size.rs, crates/torin/src/measure.rs, crates/torin/src/values/size.rs, crates/torin/tests/test.rs, examples/fill_size.rs
=> feat: New `fill` mode for width and height

examples/tic_tac_toe.rs
Closes https://github.com/marc2332/freya/issues/404
=> fix: Fix Tic Tac Toe example

crates/renderer/src/window.rs, examples/cloned_editor.rs, examples/plugin.rs, examples/virtual_scroll_view.rs
Fixes some Clippy warnings in the workspace + examples
=> Fix a couple Clippy warnings

crates/hooks/src/use_animation_transition.rs, crates/renderer/src/event_loop.rs
Depends on https://github.com/marc2332/freya/pull/496
=> fix: Emit `mouseleave` when cursor leaves the window

crates/elements/src/definitions.rs, crates/freya/src/lib.rs, crates/renderer/src/elements/image.rs, crates/renderer/src/elements/svg.rs, crates/state/src/custom_attributes.rs, crates/state/src/style.rs, examples/image.rs, examples/opacity.rs, examples/svg.rs
No need to allocate on heap what is already static.
=> feat: `static_bytes_to_data`

crates/core/src/events/event_name.rs, crates/core/src/events/events_measurer.rs
There are some spelling mistakes that I found when reading the code.
I hope this is helpful for others!
=> chore: Fix spelling mistakes

Cargo.toml, crates/components/src/dropdown.rs, crates/dom/src/dom_adapter.rs, crates/elements/src/_docs/attributes/content.md, crates/elements/src/_docs/size_unit.rs, crates/elements/src/definitions.rs, crates/state/src/layout.rs, crates/state/src/values/content.rs, crates/state/src/values/mod.rs, crates/state/src/values/size.rs, crates/torin/src/measure.rs, crates/torin/src/measure_mode.rs, crates/torin/src/node.rs, crates/torin/src/torin.rs, crates/torin/src/values/content.rs, crates/torin/src/values/mod.rs, crates/torin/src/values/size.rs, crates/torin/tests/size.rs, examples/content_fit.rs, examples/dropdown.rs
Constrain cross axis unsized bounds to the biggest inner element.
=> feat: `content` attribute

crates/components/src/accordion.rs, crates/components/src/loader.rs, crates/components/src/menu.rs, crates/components/src/snackbar.rs, crates/components/src/switch.rs, crates/freya/src/_docs/animating.rs, crates/hooks/src/use_animation.rs, crates/hooks/tests/use_animation.rs, examples/animation.rs, examples/performance_overlay_plugin.rs, examples/progress_bar.rs, examples/snackbar.rs
Further simplification of usage for `use_animation`
=> feat: Simplified `use_animation`

crates/components/src/scroll_views/virtual_scroll_view.rs, examples/cloned_editor.rs
Make optional the caching of elements in `VirtualScrollView`
=> feat: Optional `VirtualScrollView` caching

book/src/differences_with_dioxus.md, book/src/faq.md, book/src/getting_started.md, book/src/index.md
So this is probably my first ever commit to a public repo on GitHub so here we go
- Went through the /book/src/ folder and edited some sentences (an "a" here, a fixed typo there, etc.)
- fixed a little indentation thing in index.md
Please let me know if I do anything wrong because I've only ever pushed to personal projects before
=> Very minor grammatical edits

crates/elements/src/_docs/color_syntax.rs, crates/state/src/values/color.rs, crates/state/tests/parse_color.rs
=> Support-Hex-colors

crates/hooks/src/use_platform.rs, examples/window_fullscreen.rs, examples/window_min_max.rs
Added window features using the new `with_window` event.
- `maximize_window`: When called, maximizes the window if not maximized, or de-maximizes the window if already maximized (standard behaviour).
- `minimize_window`: When called, minimizes the window.
- `fullscreen_window`: When called, fullscreens the window if not fullscreened, or de-fullscreens the window if already fullscreen.
=> feat: `min/max/fullscreen window` in `use_platform`.

book/src/differences_with_dioxus.md, book/src/faq.md
Closes https://github.com/marc2332/freya/issues/593
=> docs: Update the differences with Dioxus doc

crates/hooks/src/text_editor.rs, crates/hooks/tests/use_editable.rs
Support selecting all the text with `Ctrl/Meta + A`
=> feat: Select all text

.github/workflows/dioxus_rust.yml, patches/dioxus_main_branch.patch
Closes https://github.com/marc2332/freya/issues/614
=> chore: Run against main branch of Dioxus every 3 days

crates/devtools/src/lib.rs, crates/devtools/src/node.rs, crates/devtools/src/tabs/layout.rs, crates/devtools/src/tabs/style.rs, crates/devtools/src/tabs/tree.rs
Closes https://github.com/marc2332/freya/issues/656
=> feat: Persisted devtools routing

crates/freya/Cargo.toml
Closes https://github.com/marc2332/freya/issues/665
=> feat: Do not re-export freya-testing

crates/devtools/src/lib.rs, crates/devtools/src/tabs/layout.rs, crates/devtools/src/tabs/style.rs
Depends on https://github.com/marc2332/freya/pull/667
=> feat: Persist devtools node inspector routing

Cargo.toml, crates/components/src/lib.rs, crates/components/src/tree.rs, examples/file_explorer.rs
Closes https://github.com/marc2332/freya/issues/680
=> feat: Tree builder utilities for components

crates/hooks/src/text_editor.rs, crates/hooks/tests/use_editable.rs
Closes https://github.com/marc2332/freya/issues/356
=> feat: Replace selected text with the new insert

crates/renderer/src/config.rs, crates/renderer/src/renderer.rs, examples/launch_setup.rs
Closes https://github.com/marc2332/freya/issues/695
=> fix: Fix some inconsitencies with the winit 0.30 update

crates/renderer/src/renderer.rs
Closes https://github.com/marc2332/freya/issues/700
=> feat: Only send keydowns when the window is focused

crates/native-core/Cargo.toml
=> Revert "fix(deps): update rust crate dashmap to v6"

crates/components/src/scroll_views/scroll_view.rs, crates/components/src/scroll_views/virtual_scroll_view.rs, examples/scroll.rs
Closes https://github.com/marc2332/freya/issues/722
=> feat: Change the wheels scroll based on the direction

crates/components/src/input.rs, crates/hooks/src/theming/dark.rs, crates/hooks/src/theming/light.rs, crates/hooks/src/theming/mod.rs
Closes https://github.com/marc2332/freya/issues/780
=> feat: Move `shadow` of `Input` to `InputTheme`

rust-toolchain.toml
https://github.com/tuffy/bitstream-io/issues/23
=> chore: Rust 1.80.1

crates/engine/src/mocked.rs, crates/state/src/font_style.rs
❓ 
This fixes underline decoration.
=> fix: Use individual methods to set decoration

crates/components/src/progress_bar.rs, crates/hooks/src/theming/dark.rs, crates/hooks/src/theming/light.rs, examples/switch_theme.rs
=> feat: Refreshed theme colors

crates/core/src/elements/rect.rs, crates/core/src/render/compositor.rs, crates/torin/src/geometry.rs
=> fix: Proper incremental redraws for elements with outer or center borders

crates/native-core/src/events.rs
Closes https://github.com/marc2332/freya/issues/887
=> fix: Dont trigger mouse enter on touch move

crates/torin/src/measure.rs
Closes https://github.com/marc2332/freya/issues/893
=> fix: Properly adjust accumulated sizes when using padding

crates/core/src/events/events_measurer.rs, crates/core/src/events/nodes_state.rs, crates/core/tests/pointer_events.rs
Closes https://github.com/marc2332/freya/issues/895
=> fix: Filter enter events properly, regression of #895

book/src/setup.md
adding NixOS setup documentation via a flake.nix, as mentioned on Discord.
=> Add NixOS setup

crates/components/src/image.rs, crates/components/src/lib.rs, examples/import_image.rs
Closes https://github.com/marc2332/freya/issues/847
Closes https://github.com/marc2332/freya/issues/111
=> feat: `import_image`

crates/state/src/values/gradient.rs
=> fix: linear gradient angles

README.md, crates/components/src/slider.rs, examples/floating_editors.rs, examples/opacity.rs, examples/opengl_rtt.rs, examples/progress_bar.rs, examples/switch_theme.rs, examples/text.rs
Depends on https://github.com/marc2332/freya/pull/910
=> feat: Move sliders with keyboard

crates/core/src/render/skia_measurer.rs, crates/torin/src/custom_measurer.rs, crates/torin/src/dom_adapter.rs, crates/torin/src/measure.rs, crates/torin/src/torin.rs
Kinda regression of https://github.com/marc2332/freya/pull/919
=> fix: Layout references not triggering

Cargo.toml, crates/renderer/src/config.rs, crates/renderer/src/renderer.rs, crates/renderer/src/window_state.rs
Closes https://github.com/marc2332/freya/issues/943
=> feat: Event Loop Builder hook

crates/renderer/src/app.rs, crates/renderer/src/window_state.rs
Closes https://github.com/marc2332/freya/issues/966
=> fix: Create accesskit adapter before making window visible

crates/core/src/elements/utils.rs, crates/core/src/render/compositor.rs
Closes https://github.com/marc2332/freya/issues/953
=> feat: Consider antialising for incremental rendering

book/src/setup.md, crates/freya/src/_docs/development_setup.rs
Closes https://github.com/marc2332/freya/issues/960
=> docs: Update Windows's setup instructions

crates/core/src/node.rs, crates/devtools/Cargo.toml, crates/devtools/src/node.rs
Closes https://github.com/marc2332/freya/issues/969
=> feat: Show role alongside tag in devtools inspector

crates/components/src/hooks/use_form.rs, crates/components/src/input.rs, crates/hooks/src/editor_history.rs, crates/hooks/src/rope_editor.rs, crates/hooks/src/text_editor.rs, examples/input.rs
Closes https://github.com/marc2332/freya/issues/1060
=> feat: `onvalidate` function for `Input`

crates/components/src/image.rs, crates/components/src/network_image.rs, crates/components/src/svg.rs, examples/animated_overflow_content.rs, examples/import_image.rs, examples/import_svg.rs, examples/website.rs
Closes https://github.com/marc2332/freya/issues/1084
=> feat: Simplified `import_image` and `import_svg` macros

Cargo.toml, examples/animated_tabs.rs
https://x.com/mkenzo_8/status/1885789608975245371
=> feat: Cooler animated tabs example

crates/core/src/render/pipeline.rs
Effects should be applied after having clipped the viewports
=> fix: Clip scale effects

crates/hooks/src/theming/base.rs, crates/hooks/src/theming/mod.rs, crates/hooks/src/theming/themes.rs
Closes https://github.com/marc2332/freya/issues/1107
=> feat: Use a darker color for the focused border of `FilledButton`

crates/elements/src/attributes/transform_attributes.rs
Closes https://github.com/marc2332/freya/issues/1075
=> docs: Transform attributes docs

book/src/setup.md, crates/freya/src/_docs/development_setup.rs
Closes https://github.com/marc2332/freya/issues/1063
=> docs: Update setup requirements

crates/elements/src/_docs/color_syntax.rs, examples/gradient.rs
Closes https://github.com/marc2332/freya/issues/786
=> docs: Add Gradients docs

crates/core/src/values/position.rs, crates/torin/src/values/position.rs
Closes https://github.com/marc2332/freya/issues/1121
=> fix: Save non-stacked positions until position is swapped

crates/core/src/render/pipeline.rs
Closes https://github.com/marc2332/freya/issues/1126
=> fix: Render devtools wireframe after all elements have been rendered

crates/components/src/accordion.rs
Closes https://github.com/marc2332/freya/issues/1127
=> feat: Allow passing initial state to `Accordion`

crates/core/src/elements/rect.rs, crates/core/src/render/utils/borders.rs, crates/engine/src/mocked.rs
Closes https://github.com/marc2332/freya/issues/1133
=> fix: Round in borders to prevent antialising

crates/components/src/dropdown.rs, crates/core/src/events/events_measurer.rs, crates/core/tests/events_emitting.rs, crates/native-core/src/events.rs
Closes https://github.com/marc2332/freya/issues/1167
=> fix: measure collateral events of derived events

crates/core/tests/events_emitting.rs, crates/native-core/src/events.rs
Closes https://github.com/marc2332/freya/issues/1180
=> fix: Do not bubble keyboard global events

crates/components/src/loader.rs, examples/loader.rs
=> Feat: customizable loader size

crates/components/src/body.rs, examples/button.rs, examples/documents_editor.rs, examples/preferred_theme.rs, examples/router.rs, examples/shader_editor.rs, examples/tab.rs
Closes https://github.com/marc2332/freya/issues/1161
=> feat: Support `main_align` and `cross_align` in `Body` component

crates/components/src/hooks/use_form.rs, crates/components/src/input.rs, examples/input.rs
Closes https://github.com/marc2332/freya/issues/1231
=> feat: `onfocuschange` for `Input`

crates/components/src/table.rs
Closes https://github.com/marc2332/freya/issues/1222
=> feat: Docs example in `Table` component

crates/components/Cargo.toml, crates/components/src/input.rs, crates/components/src/scroll_views/use_scroll_controller.rs
Closes https://github.com/marc2332/freya/issues/1192
=> fix: Remove non important dioxus warnings

examples/file_picker.rs
Closes https://github.com/marc2332/freya/issues/1130
=> docs: Add an example showcasing how to use `rfd`

Cargo.toml, crates/freya/src/lib.rs
No more need to add freya and dioxus, just freya is enough
=> feat: Re-export dioxus

crates/elements/src/_docs/size_unit.rs
Closes https://github.com/marc2332/freya/issues/1202
=> docs: Clarify `fill` size value

crates/components/src/network_image.rs, crates/hooks/src/use_asset_cacher.rs, crates/hooks/src/use_init_native_platform.rs, crates/hooks/tests/use_asset_cacher.rs
- Use ReactiveContext
- Automatic suscription and clean up
- Reuses inflight requests (Closes https://github.com/marc2332/freya/issues/1254)
=> feat: Rethink `AssetCacher`

crates/core/src/layers.rs, crates/core/src/states/layer.rs, crates/elements/src/events/pointer.rs, crates/native-core/src/events.rs
Depends on https://github.com/marc2332/freya/pull/1320
=>  feat: `oncaptureglobalpointerup` event
